### Essential Imports

In [1]:
import pandas as pd
import numpy as np
from numpy.random import randn as rn

**Question 1:**


Create a 4X2 integer array and Prints its attributes
Note: The element must be a type of unsigned int16. And print the following Attributes:
–
The shape of an array.
Array dimensions.
The Length of each element of the array in bytes.

In [2]:
# imported randn as rn
a = rn(4,2)
new_arr = a.astype('int16')
print(new_arr)
print("\nThe shape of an array","-"*40,new_arr.shape,"\nArray dimensions","-"*40,new_arr.ndim,"\nThe length of each element of the array in bytes","-"*40,new_arr.size,sep="\n")

[[0 1]
 [0 0]
 [0 0]
 [1 0]]

The shape of an array
----------------------------------------
(4, 2)

Array dimensions
----------------------------------------
2

The length of each element of the array in bytes
----------------------------------------
8


**Question 2:**

Create a 5X2 integer array from a range between 100 to 200 such that the
difference between each element is 10.

In [3]:
arr = np.arange(100,200,10)
arr.reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

**Question 3:**

Following is the provided numPy array. return array of items in the third column
from all rows
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [4]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [5]:
sampleArray[:,-1]

array([33, 66, 99])

**Question 4:**

Following is the given numpy array return array of odd rows and even columns
import numpy..........
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])


Expected Output:
Printing Input Array
[[ 3 6 9 12]
[15 18 21 24]

[27 30 33 36]
[39 42 45 48]
[51 54 57 60]]


Printing array of odd rows and even columns
[[ 6 12]
[30 36]
[54 60]]

In [6]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

print("\nPrinting Input Array","-"*40,sampleArray,"\nPrinting array of odd rows and even columns","-"*60,sampleArray[::2,1::2],sep="\n")


Printing Input Array
----------------------------------------
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing array of odd rows and even columns
------------------------------------------------------------
[[ 6 12]
 [30 36]
 [54 60]]


**Question 5:**

Extract all odd numbers from arr
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:
#> array([1, 3, 5, 7, 9])

In [7]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

**Question 6:**

Replace all odd numbers in arr with -1.
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:
#> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])


In [8]:
# Input
arr = np.array([0,1,2,3,4,5,6,7,8,9])

# Output
op = np.where(arr%2!=0,-1,arr)
op

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**Question: 7**

Replace all odd numbers in arr with -1 without changing arr
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:
out
#> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
arr
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
out = np.where(arr%2!=0,-1,arr)
print("\nDesired Output","*"*40,out,"\nAnd the array is:","*"*40,arr,sep="\n")


Desired Output
****************************************
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

And the array is:
****************************************
[0 1 2 3 4 5 6 7 8 9]


**Question 8:**

Convert a 1D array to a 2D array with 2 rows 
Input:
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:
#> array([[0, 1, 2, 3, 4],
#> [5, 6, 7, 8, 9]])
9. Create a 3x3x3 array with random values

In [10]:
arr = np.arange(10)
print("\nThe orignal array","-"*40,arr,sep="\n")

new = arr.reshape(2,5)
print("\nDesired Output","-"*40,new,sep="\n")


The orignal array
----------------------------------------
[0 1 2 3 4 5 6 7 8 9]

Desired Output
----------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]


**Question 9:**
Create a 3*3*3 array with random values


In [11]:
r = rn(3,3,3)
print("\n3 X 3 X 3 matrix with random values.","-"*40,r,sep="\n")


3 X 3 X 3 matrix with random values.
----------------------------------------
[[[-1.07487327  1.50253027  1.51848453]
  [ 1.11788942 -0.75970397 -0.13420544]
  [-0.98118786  0.39451177 -1.12658748]]

 [[ 0.34534718  1.07059931 -0.86810974]
  [ 0.68013361  0.70698509  0.27873591]
  [ 0.53510818 -0.85875972  0.74636469]]

 [[ 2.03994182  0.98009227 -1.20221126]
  [-1.03110611 -0.50138672 -0.01255967]
  [-0.73715178  0.01601941 -0.04166292]]]


**Question 10:**

Write the NumPy program to create a null vector of size 10 and update sixth value to 11.

In [12]:
a = np.zeros(10)
print("\nNull vector of size = 10","-"*40,a," ",sep="\n")
a[6]=11
print("\nAfter updating sixth value to 11","-"*40,a," ",sep="\n")


Null vector of size = 10
----------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 

After updating sixth value to 11
----------------------------------------
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
 


**Question 11:**

Write a NumPy program to convert a list and tuple into arrays.

In [13]:
list1 = [1, 2, 3, 4, 5, 6]
tuple1 = ('A', 'B', 'C', 'D', 'E')
print("\nList and Tuple","-"*40,list1,tuple1," ",sep="\n")

nplist = np.array(list1)
nptuple = np.array(tuple1)
print("\nAfter converting to array","-"*40,nplist,nptuple," ",sep="\n")


List and Tuple
----------------------------------------
[1, 2, 3, 4, 5, 6]
('A', 'B', 'C', 'D', 'E')
 

After converting to array
----------------------------------------
[1 2 3 4 5 6]
['A' 'B' 'C' 'D' 'E']
 


**Question 12**

Write a NumPy program to create a 2-D array whose diagonal equals [4,5,6,8] and 0's elsewhere.


In [14]:
a = [4,5,6,8]
arr = np.zeros(shape=(4,4))
print("\n2-D array with O's everywhere","-"*40,arr,sep="\n")
for i in range(4):
    arr[i,i]=a[i]

print("\n2-D arrray with diagonal changed diagonal values","-"*50,arr,sep="\n")
    




2-D array with O's everywhere
----------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2-D arrray with diagonal changed diagonal values
--------------------------------------------------
[[4. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]
