In [4]:
import numpy as np
import pandas as pd
import random
import math
import re


In [ ]:
# Question: 1
"""
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a
single line.
"""

# for i in range(2000,3201):
#     if i%7==0 and i%5!=0:
#         print(f"{i},",end="")
        
numbers = [i for i in range(2000, 3201) if i%7==0 and i%5 != 0]
print(numbers)

In [ ]:
# Question: 2
"""
Write a program which can compute the factorial of a given numbers. The results should be printed in
a comma-separated sequence on a single line. Suppose the following input is supplied to the program: 8
Then, the output should be: 40320

"""
n = int(input("Enter a integer: "))

# def factorial(n):
#     # n is number
#     if n <=1:
#         return 1
#     else:
#         return n * factorial(n-1)
    



# another way

def factorial(n):
    fact = 1
    if n <=1:
        return fact
    else:
        for i in range(1,n+1):
            fact *= i
        return fact
            
factorial(n)

In [ ]:
# Question 3:
"""
With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is
an integral number between 1 and n (both included). and then the program should print the dictionary.
Suppose the following input is supplied to the program: 8
Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}
"""
n = int(input("Enter a number: "))
{i:i*i for i in range(1,n+1)}

In [ ]:
# Question 4:
"""
Write a program which accepts a sequence of comma-separated numbers from console and generate a list 
and a tuple which contains every number. Suppose the following input is supplied to the program:
34,67,55,33,12,98, Then, the output should be:
['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')
"""
n = input(" ")

list1 = n.split(",")
tuple1 = tuple(list1)

print(list1)
print(tuple1)

In [2]:
# Question 5:
"""
Define a class which has at least two methods: 
getString: to get a string from console input
printString: to print the string in upper case. Also please include simple test function to test the class methods.
"""

class Str:
    def __init__(self):
        self.s= None
        
        
    def getString(self):
        self.s = input()
                
    def printString(self):
        print(self.s.upper())
        


obj = Str()
obj.getString()
obj.printString()


This is sparta
THIS IS SPARTA


In [5]:
# Question: 6
"""
Write a program that calculates and prints the value according to the given
formula:
Q = Square root of [(2 * C * D)/H] Following are the fixed values of C and H:
C is 50. H is 30.  D is the variable whose values should be input to your program in a comma-
separated sequence. 
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24
"""


d = [int(i) for i in input("").split(",")]
list(map(lambda d : int(math.sqrt((2*50*d)/30)),d))


100,150,180


[18, 22, 24]

In [6]:
# Question 7:
"""
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the
array should be i*j. Note: i=0,1.., X-1; j=0,1,¡Y-1.
"""


# Creating a matrix  Method 1)

# x,y = (3,5)
# matrix = np.fromfunction(lambda i,j:i*j ,(x,y))
# matrix


# Creating a matrix Method 2)




XY = [int(i) for i in input("").split(",")]

main_list = []

for r in range(0,XY[0]):
    b= []
    for c in range(0,XY[1]):
        b.append(r*c)
    main_list.append(b)
    
    
print(np.array(main_list))
         
# arr = [[x*y for y in range(XY[1])] for x in range(XY[0])]
# arr

3,5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [7]:
# Question: 8
"""
Write a program that accepts a comma separated sequence of words as input and prints the words in a 
comma-separated sequence after sorting them alphabetically. Suppose the following input is supplied to the program:
without,hello,bag,world Then, the output should be: bag,hello,without,world
"""
strings = input("Provide comma separated sequence of words:  ")
lst = list(strings.split(","))
print(sorted(lst))


Provide comma separated sequence of words:  without,hello,bag,world
['bag', 'hello', 'without', 'world']
['without', 'hello', 'bag', 'world']


In [8]:
# Question: 9
"""
Write a program that accepts sequence of lines as input and prints the lines after making all characters in the
sentence capitalized. Suppose the following input is supplied to the program: Hello world Practice makes perfect
Then, the output should be: HELLO WORLD PRACTICE MAKES PERFECT
"""



line = []
while True:
    string = input("")
    if string:
        line.append(string)
    else:
        break
for i in line:
    print(i.upper())

hello world
practice makes perfect

HELLO WORLD
PRACTICE MAKES PERFECT


In [ ]:
# Question: 10
"""
Write a program that accepts a sequence of whitespace separated words as input and prints the words after
removing all duplicate words and sorting them alphanumerically. Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world
"""
inpt = input("Say something: ")

l = set(inpt.split(' '))
result = sorted(list(l))
print(result)


In [ ]:
# Qustion: 11
"""
Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then 
check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a
comma separated sequence. Example: 0100,0011,1010,1001
Then the output should be: 1010
"""

sample = ['0100','0011','1010','1001']
for i in sample:
    dec = int(i,2) # converting binary to decimal
    if dec%5 == 0:
        print(i)


In [ ]:
# Question: 12
"""
Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of 
the number is an even number. The numbers obtained should be printed in a comma-separated sequence on a single line.
"""
result = []
for i in range(1000,3001):
    d1 = i%10  # unit digit
    d2 = (i//10)%10
    d3 = (i//100)%10
    d4 = (i//1000)%10
    if d1%2 == 0 and d2%2 == 0 and d3%2 == 0 and d4%2 == 0:
        result.append(i)
        
print(result)
        
    



In [ ]:
# Question: 13
"""
Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following
input is supplied to the program: hello world! 123 Then, the output should be: LETTERS 10 DIGITS 3
"""

s = input("")
d = 0
l = 0
for i in s:
    if i.isdigit():
        d+=1
    elif i.isalpha():
        l+=1
print(f"Letter: {l} \nDigits: {d}")

In [ ]:
# Question: 14
"""
Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.
Suppose the following input is supplied to the program: Hello world! Then, the output should be:
UPPER CASE 1
LOWER CASE 9
"""

sentence = input("")

u = 0
l = 0

for i in sentence:
    if i.isupper():
        u +=1
    elif i.islower():
        l +=1
        
print(f"UPPER CASE: {u} \nlower case: {l}")
            

In [ ]:
# Question: 15
"""
Write a program that computes the net amount of a bank account based a transaction log from console input.
The transaction log format is shown as following: 
D 100
W 200, D means deposit while W means withdrawal.
Suppose the following input is supplied to the program:
D 300
D 300
W 200
D 100
Then, the output should be: 500
"""

Total = 0
while True:
    inpt = input("")
    if inpt:
        t = inpt.split(" ")
        if t[0]=='d' or t[0]=='D':
            Total += int(t[1])
        elif t[0]=='w' or t[0]=='W':
            Total -= int(t[1])
    else:
        break
            
print(f"Balance: {Total}")

In [ ]:
# Question: 16
"""
A website requires the users to intput username and passord to register.
Write a program to check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will
check them according to the above criteria. Passwords that match the criteria
are to be printed, each separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1
"""

inpt = input()

l = [i for i in inpt.split(",")]

for a in l:
    if len(a)<6 or len(a)>12:
        continue        
    elif re.search("[a-z]",a) is None:
        continue
    elif re.search("[A-Z]",a) is None:
        continue
    elif re.search("[0-9]",a) is None:
        continue
    elif re.search("[$#@]",a) is None:
        continue
    else:
        print(a)
        
    

In [ ]:
# Question: 17
"""
A robot moves in a plane starting from the original point (0,0). The robot can move
toward UP, DoWN, LEFT and RIGHT with a given steps. The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
"""

x,y = 0,0
while True:
    
    d = [i for i in input().split(" ")]
    if len(d)>1:
        if d[0].lower() == "up":
            y += int(d[1])

        elif d[0].lower() == "down":
            y -= int(d[1])

        elif d[0].lower() == "left":
            x -= int(d[1])

        elif d[0].lower() == "right":
            x += int(d[1])
    else:
        result = math.sqrt(x**2 + y**2)
        print(round(result))
        break

In [ ]:
# Question: 18
"""
write a program to compute the frequency of the words form the input. The output should
after sorting the key alphanumerically.
suppose the following input is supplied to the program:
New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.

"""

a = input()
x = sorted(a.split(" "))
l = []
for i in x:
    if i not in l:
        l.append(i)
        print(f"{i}:{x.count(i)}")
        

In [ ]:
# Question: 19
"""
Write a method which can calculate square value of number
Hints:
Using the ** operator
"""
x = int(input())
print(f"square of the {x} is: {x**2}")

In [ ]:
# Question: 20
"""
Define a class, which have a class paramter and have a same instance paramter.

"""

class Parameter:
    def __init__(self,side):
        self.side = side
        
    def square(self):
        return 4*self.side
    
a = Parameter(4)
a.square()

In [ ]:
# Question: 21
"""
Define a function that can convert a integer into a string and print it in console.
"""

def int_to_str(i):
    return str(i)

int_to_str(100)

In [ ]:
# Question: 22
"""
Define a function that can recieve two integral numbers in string form and compute their
sum and then print it in console.
"""

def sum(s):
    n = s.split(" ")
    return int(n[0]) + int(n[1])


s = input()
sum(s)

In [ ]:
# Question: 23
"""
Define a function that can accept two strings as input and print the string with maximun length in console. If two strings have t
he same length, then the function should print all strings line by line.
"""
def max_length(a,b):
    if len(a)> len(b):
        print(a)
    elif len(b)>len(a):
        print(b)
    else:
        print(a)
        print(b)

a = input("a: ")
b = input("b: ")

max_length(a,b)

In [ ]:
# Question: 24
"""
Define a function which can print a dictionary where the keys are numbers
between 1 and 3( both included) and the values are square of keys.
"""

{k:k**2 for k in range(1,4)}

In [ ]:
# Question: 25A
"""
Define a function which can print a dictionary where the keys are numbers
between 1 and 20 (both included) and  the values are square of keys.
"""

{k:k**2 for k in range(1,21)}

In [ ]:
# Question: 25B
"""
Write a program which accepts a string as input to print "Yes" if the string is "yes" 
or "YES", otherwise print "No".
"""
a = input()
if a in ["Yes","yes","YES"]:
    print('Yes')
else:
    print("NO")

In [ ]:
# Question: 26
"""
Write a program which can filter even numbers in list by using filter funtion.
The lsit is: [1,2,3,4,5,6,7,8,9,10]

"""
l = list(range(1,11))
result = list(filter((lambda x: x%2 == 0),l))
print(result)

In [ ]:
# Question: 27
"""
Write a program which can map() to make a list whose element are square of elements in
[1,2,3,4,5,6,7,8,9,10]
"""
l = list(range(1,11))
result = list(map((lambda x:x**2),l))
result

In [ ]:
# Question: 28
"""
Write a program which can map() and filter() to make a list whose elements are square fo even
number in [1,2,3,4,5,6,7,8,9,10]
"""
l = list(range(1,11))
result = list(map((lambda i:i**2),(filter((lambda x:x%2==0),l))))
result

#or
# [i**2 for i in l if i%2==0]